name: Node.js CI (SQLite)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Setup .env.test
        run: |
          echo "NODE_ENV=test" >> .env.test
          echo "DB_DIALECT=sqlite" >> .env.test
          echo "DB_STORAGE=:memory:" >> .env.test
          echo "JWT_SECRET=testsecret" >> .env.test

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test
